CC = gcc
CFLAGS = -Wall -Werror -W

tp1: tp1_1.o tp1_2.o tp1_3.o
	$(CC) -o $@ $^

tp1_1.o: tp1_1.c
	$(CC) $(CFLAGS) -c $^

tp1_2.o: tp1_2.c
	$(CC) $(CFLAGS) -c $^ 

tp1_3.o: tp1_3.c
	$(CC) $(CFLAGS) -c $^ 
